name: tigramite2_conda
dependencies:
    - python=3
    - numpy>=1.10.0
    - scipy>=0.17.0
    - scikit-learn>=0.18.1
    - matplotlib>=1.5.1
    - networkx=1.10.0
    - cython>=0.26
    - pip
    - pip:
        - statsmodels >= 0.6.0